#super user access to excute build
sudo: required

services:
   - docker
#to build image in travis docker
before_install:
   - docker build -t aj14314/docker-react -f Dockerfile.dev .
#to run test in travis docker
script:
   - docker run -e CI=true aj14314/docker-react npm run test -- --coverage
#to deploy image in aws
deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "docker-react"
   env: "Dockerreact-env"
   bucket_name: "elasticbeanstalk-us-east-1-801528572440"
   bucket_path: "docker-react"
   #master branch only
   on:
     branch: master
   access_key_id: $AWS_SECRET_KEY
   secret_access_key: $AWS_SECRET_KEY
