#super user access to excute build
sudo: required

services:
   - docker

before_install:
   - docker build -t aj14314/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true aj14314/docker-react npm run test