version: '3'

services: 
    react-web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app #. folder of the local to app folder of container
#service to handle our test suite
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm","run","test"]