FROM node:10-alpine3.11

WORKDIR '/app'

COPY package.json .

RUN npm install

#can remove because we have mapped this to a volume for dev but for prod we may need it
COPY . .

CMD ["npm","run","start"]